
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =              60
     no. of nonzeroes in lower triangle of a =             534
     no. of nonzeroes in the factor l        =            1914
     ratio of nonzeroes in factor (min/max)  =          0.2097
     number of super nodes                   =               5
     maximum order of a front matrix         =              24
     maximum size of a front matrix          =             300
     maximum size of a front trapezoid       =             300
     METIS reordering method used 
     no. of floating point ops for factor    =      1.1386D+04
     no. of floating point ops for solve     =      2.7600D+03
     ratio of flops for factor (min/max)     =          0.3903
     ratio of allocated memory (max/min)     =          1.0290
     number of positive pivots               =              60
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000275
     time (cpu & wall) for ordering          =        0.000000        0.002041
     time (cpu & wall) for other matrix prep =        0.000000        0.002819
     time (cpu & wall) for value input       =        0.000000        0.000033
     time (cpu & wall) for matrix distrib.   =        0.000000        0.005630
     time (cpu & wall) for numeric factor    =        0.015625        0.002924
     computational rate (gflops) for factor  =        0.000729        0.003894
     time (cpu & wall) for numeric solve     =        0.015625        0.023691
     computational rate (gflops) for solve   =        0.000177        0.000117
     effective I/O rate (GB/sec) for solve   =        0.000658        0.000434

     no input or output performed

  Solver Memory allocated on core    0       =        0.268 MB
  Solver Memory allocated on core    1       =        0.264 MB
  Solver Memory allocated on core    2       =        0.263 MB
  Solver Memory allocated on core    3       =        0.260 MB
  Total Solver Memory allocated by all cores =        1.054 MB

