
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             828
     no. of nonzeroes in lower triangle of a =           12625
     no. of nonzeroes in the factor l        =           21070
     ratio of nonzeroes in factor (min/max)  =          0.3436
     number of super nodes                   =              51
     maximum order of a front matrix         =              33
     maximum size of a front matrix          =             561
     maximum size of a front trapezoid       =             516
     METIS reordering method used 
     no. of floating point ops for factor    =      3.1575D+05
     no. of floating point ops for solve     =      5.8516D+04
     ratio of flops for factor (min/max)     =          0.3640
     ratio of allocated memory (max/min)     =          1.2398
     number of positive pivots               =             828
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000131
     time (cpu & wall) for ordering          =        0.000000        0.001950
     time (cpu & wall) for other matrix prep =        0.000000        0.003393
     time (cpu & wall) for value input       =        0.000000        0.000129
     time (cpu & wall) for matrix distrib.   =        0.000000        0.006058
     time (cpu & wall) for numeric factor    =        0.015625        0.012833
     computational rate (gflops) for factor  =        0.020208        0.024604

     no input or output performed

  Solver Memory allocated on core    0       =        0.515 MB
  Solver Memory allocated on core    1       =        0.508 MB
  Solver Memory allocated on core    2       =        0.521 MB
  Solver Memory allocated on core    3       =        0.420 MB
  Total Solver Memory allocated by all cores =        1.965 MB

