
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1566
     no. of nonzeroes in lower triangle of a =           12207
     no. of nonzeroes in the factor l        =           41983
     ratio of nonzeroes in factor (min/max)  =          0.8774
     number of super nodes                   =             134
     maximum order of a front matrix         =              36
     maximum size of a front matrix          =             666
     maximum size of a front trapezoid       =             588
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      6.8231D+05
     no. of floating point ops for solve     =      2.3302D+05
     ratio of flops for factor (min/max)     =          0.7987
     ratio of allocated memory (max/min)     =          1.1107
     number of positive pivots               =            1566
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.013000
     time (cpu & wall) for ordering          =        0.015625        0.009000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.002000
     time (cpu & wall) for numeric factor    =        0.015625        0.007000
     computational rate (gflops) for factor  =        0.043668        0.097473

     no input or output performed

  Solver Memory allocated on core    0       =        0.533 MB
  Solver Memory allocated on core    1       =        0.501 MB
  Solver Memory allocated on core    2       =        0.532 MB
  Solver Memory allocated on core    3       =        0.556 MB
  Total Solver Memory allocated by all cores =        2.122 MB

